### ISSUE TITLE
Bryan && Raquel && (NPM || Community || Robots || Infinity)

### ISSUE THREAD

**Issue by dlindahl** [sacjs/sacjs.github.io#10]
Dear @rockbot && @bryan-m-hughes,

We at SacJS would like to formally invite you to speak at one of our monthly meetups. We are still a new community group and many of our members seem to be relatively new to Javascript (though we have some overachievers) and certainly new to speaking. We were wondering if you would like to come talk to our members about... really anything. 

Given both of your backgrounds, here are some starter ideas:

* NPM (how to package manage)
* Server-side JS basics
* NodeBots
* The Javascript community from local meetups (ManhattanJS, JS.LA, etc.), through smaller events (NodeBots, JSFest, ThunderplainsConf), and up to JSConf or FluentConf
* Speaking! (We've had no volunteers :cry:) 
* Anything!

I've asked you both either in person or via the Internet, and you've both been agreeable to the idea. So this serves as an (overly formal :wink:) way to kick off planning. We have openings as early as March, though a specific date has not yet been locked in. We'd like to shoot for an hour of talks (2 30min, 3 20min, etc.), so if you have any friends you'd like to bring with you, please do!

So what say you? :pray: 

-- :heart: Sacramento

**Comment by bryan-m-hughes** [comment]
Do you have a standard/preferred night you host meetups on? My March calendar looks surprisingly open, but Wednesdays are generally out, as are the first and third Thursdays of the month.

As for topic, I'm pretty flexible. I can give a talk on speaking, although I don't think I would want to give the one gave at ForwardJS...I'm kinda picky with that one 😉. I could certainly throw one together on the more practical sides of speaking (how to create a proposal, how to structure a talk, etc). That aside, NodeBots are probably my strongest area, but I can give a talk on any of those topics.

**Comment by dlindahl** [comment]
@bryan-m-hughes We are still really new and trying to figure things out. So no, we don't quite have a preferred night yet. Wednesdays usually work best given everything else that happens in this town. However, with enough pre-planning, I'm sure we can get a Thursday to work! I know you said Wednesdays are out, but we just had a cancellation for our meetup on the 25th so are sort of empty right now. If you can make it or if you know of anyone else that would like to join us, please let us know!

While your ForwardJS talk was pretty good, I feel like it might be a bit heavy for our crowd. Like I said, we are incredibly new and still trying to figure out where everyone is at as far as skill level with both coding and public speaking. A practical and empowering talk on Speaking 101 would be awesome. I have no idea what I'm doing but even I have figured out how to get up and talk to the group :smile:.

I'd love to do something NodeBots related, but our very first meeting was with Tessel (which went incredibly well), so I don't want to double-up on hardware. Depending on how this month goes, March would be doable for a NodeBots event. Does NodeBotsSF meet on a weekday or weekend?

Is Rdio doing anything noteworthy with Javascript? Would anyone you've met through SF-based events be willing to tag team with you on an evening of talks?

@rockbot, I know you have been busy schooling everyone on how to MC, but any chance we could get up to come up on the 25th? Bring an entourage with you? If not, would March work?

Also, even if this doesn't work out, I want to thank you both so much for even considering coming up. Sacramento has a nascent tech scene and I feel like there is something to be made here. Pulling talent from our neighbors by the Bay should give us enough momentum to make something stick. As you both know, the JS community is strong and I want to share that familial feeling with everyone here.

:heartpulse:

**Comment by bryan-m-hughes** [comment]
@dlindahl So I actually can make it on the 25th, huzzah! I'm currently working on a short Speaking 101 talk for another local meetup here, so I can expand that into a full 30 minute talk.

NodeBots SF meets on the third Thursday of every month. We've found having a regular cadence seems to help with scheduling. Since there was a Tessel meetup recently, maybe we should wait a few months?

As for Rdio, the best I can say is stay tuned. We don't really have anything already in production that I feel would make a great talk, but there is some stuff in the works that I can't talk about that might good to talk about.

I'm sure I can find someone to bring along if @rockbot and I speak on different days :).

**Comment by dlindahl** [comment]
@bryan-m-hughes: Sorry, been crazy busy with deployments. I think your idea sounds great! Are you still available to come up? Let's do this!

**Comment by bryan-m-hughes** [comment]
Yep, I'm still in! I haven't had a chance to reach out to anyone else about speaking yet, I'll try and do that today.
