### ISSUE TITLE
Rebecca Turner: A Brave New npm@5 World

### ISSUE THREAD

**Issue by iarna** [sacjs/sacjs.github.io#102]
Name: Rebecca Turner
Twitter Handle: @ReBeccaOrg
GitHub Username: iarna
Employer: npm, inc
Talk Length: 10 - 15 min

---

Title: A Brave New npm@5 World
Brief Description: npm@5 was recently released along with node 8. Learn about what's changed, what new features we have and why you should be updating now. Plus super secret hints about what's to come.

**Comment by dlindahl** [comment]
Awesome! We're looking forward to having NPM back in Sacramento! Do any other wombats want to come up and talk as well?

**Comment by dlindahl** [comment]
Hi Rebecca, just wanted to reach out and see if you had any last minute questions for us about the meetup tomorrow. If not, see you tomorrow!

**Comment by iarna** [comment]
Nope, thanks though. (Due to a calendar mishap, I actually visited the venue last week already. =D)
