### ISSUE TITLE
Community and NPM Modules

### ISSUE THREAD

**Issue by dlindahl** [sacjs/sacjs.github.io#11]
##### 6:30pm Preparation

* Get space setup (chairs, projector, etc.)

##### 7:00pm Start

* Opening remarks (thanks for coming, introduce staff, etc.)

##### 7:15pm First Talk - Bryan Hughes (Rdio)

* Bryan will be talking about talking. And community!

##### 7:35pm Second Talk - Emily Rose (Spark)

* Emily will be talking about Oakland DanceJS and the story of how they got started

##### 7:55pm Third Talk - Benjamin Coe (NPM)

* Benjamin will be giving an intro talk to NPM and how to use package managers

##### 8:15pm Finish

* Give aways

  * O'Reily give away?

  * Give away Nomad+JS tickets

    The "tickets" would be for the [March 17th meetup](http://nomadjavascript.com/march-2015/). @dlindahl will give away his slot so that two can attend the virtual meetup. All we need is full name and email address which will be forwarded to the Nomad+JS staff for registration.

* Next meetup in Match (Date TBD)

  Ask for speaker volunteers or recommendations

* Announce BeerJS and CoffeeJS sub-events

  Watch Twitter (@sac_js & @beerjs_sac) or Meetup.com for news

* Get Bryan, Emily, and Benjamin to the train station NLT **9pm** for 9:10pm train.

**Comment by dlindahl** [comment]
@samt You are off the hook ;) I just need the @sacjs/staff for logistics again. I will be picking up and dropping off from Amtrak, so whatever plan you all came up with last time should be perfect.

@a-axton If you need us there earlier to deal with chairs, etc. Please let us know.

**Comment by samt** [comment]
Awesome! I'll be there early and make sure things are ready.

**Comment by samt** [comment]
Regarding the OSCON guy, his name is Carson and I'm told he's been in contact with you already.

**Comment by dlindahl** [comment]
@sacjs/staff I'm hoping to boost our current RSVP numbers a bit. Don't forget to bug your friends and get them to RSVP!
