### ISSUE TITLE
Intro to ES6 with Mike Piccolo

### ISSUE THREAD

**Issue by dlindahl** [sacjs/sacjs.github.io#12]
I spoke with Thomas Hopkins and he indicated that he'd be willing to talk about an MVC-like library he's written.

**Comment by dlindahl** [comment]
@thomchop What is your availability on 3/18 @ 7pm?

**Comment by thomchop** [comment]
The library I mentioned, [Kindred](https://github.com/mfpiccolo/kindred), is a project of my business partner, @mfpiccolo. It's really cool and I'd like to see him demo it, but it's directed at a particular niche, and we would prefer to present on a broader topic. We'd like to give people a rundown on ES6. What do you think of that? Has anyone else taken it on at SacJS?

**Comment by dlindahl** [comment]
@thomchop An ES6 talk would be _**perfect**_! Any chance @mfpiccolo can present on the 18th?

**Comment by mfpiccolo** [comment]
Hey @dlindahl.  I am down to do a presentation on Kindred if people would be interested in something like that.  It is basically a micro js framework to help out rails projects beef up their forms without committing to a full fledged js framework like angular or ember.  

I am also cool with going along with @thomchop and presenting on generator functions or some other cool features on es6.

**Comment by dlindahl** [comment]
@mfpiccolo I would love for an ES6 talk. In fact, the topic is large enough, maybe I can convince you to give a series of talks?

I can put you down for an Intro to ES6 talk on the 18th? Something along the lines of "what is ES6 and why you should care". Then talk about the easy features like `let` vs `var` and String templates, etc.

**Comment by mfpiccolo** [comment]
@dlindahl Yeah that sounds cool.  What is the level of most of the people attending?

**Comment by dlindahl** [comment]
The level of most people attending tends to be mostly beginners with a handful of experts. I would definitely target the presentation towards people that have likely never heard of ES6. I have added an RSVP question asking the attendee about their knowledge of ES6, so I should be able to give you a bit more insight as we get closer to the meetup date.

Shoot for a 30min presentation, though if you are a bit over or under, its not a big deal.

I think closing the talk with a bit of info about how we can all start using ES6 now with tools like Babel would be a good idea as well. And if you are up for it, I'd love to have you present a couple of times about various ES6 features. There is obviously a lot of surface area to talk about there.

Thanks for volunteering to do this! I was hoping that we'd get an ES6 talk on deck quickly and you've made that a reality! 

* * *

Our meeting agenda: https://github.com/sacjs/sacjs.github.io/issues/15
Meetup Page: http://www.meetup.com/The-Sacramento-Javascript-Meetup/events/221127032/
Twitter: @sac_js
