### ISSUE TITLE
Easy front-end JavaScript testing with Cypress

### ISSUE THREAD

**Issue by decafdennis** [sacjs/sacjs.github.io#120]
Name: Dennis Stevense
Twitter Handle: @decafdennis
GitHub Username: @decafdennis
Employer: Digital Deployment
Talk Length: 20m

---

Title: Easy front-end JavaScript testing with Cypress
Brief Description: Cypress is a new(ish?) test framework that makes testing front-end code easy and fast right out of the box. I'll demonstrate how we're using it with a non-trivial real-world example, and I'll also go over some of the great recommendations from the Cypress documentation that have helped us keep our front-end tests manageable.

**Comment by dlindahl** [comment]
Hey Dennis, once I have two talk proposals in front of you. Once I know when they are available, I'll get you scheduled. Are you ok doing this talk on April 24th (with March 27 as a back-up?)

**Comment by decafdennis** [comment]
Yes, either date works for me as of now. Thanks!

**Comment by JohnRPB** [comment]
That sounds really cool... looking forward!

**Comment by dlindahl** [comment]
@decafdennis we had a cancellation for March. Are you available on March 27 to give this talk?

**Comment by decafdennis** [comment]
@dlindahl Yes!
