### ISSUE TITLE
ReactJS with Devon Lindsey & Routing with Michael Jackson

### ISSUE THREAD

**Issue by dlindahl** [sacjs/sacjs.github.io#13]
I've pinged Devon Lindsey, founder of the SF ReactJS meetup, and Michael Jackson, co-creator of React-Router, to present at a future event.

https://twitter.com/sac_js/status/572530783149154305

**Comment by dlindahl** [comment]
Hi @devonbl and @mjackson, I'd like to hold a hands-on ReactJS Workshop here in Sacramento and I'd love to have you both over to give an intro class and to offer any post-class assistance.

It is a pretty nascent idea so far, but I imagine it occurring on a Saturday or Sunday in either April or June, whenever scheduling permits. The event itself would either be free or would require a small fee that we can use to donate towards a local STEM group.

Any interest? :pray: :blush:

**Comment by devonbl** [comment]
i'd love to do something like this, michael might be more booked than I.  April is bad though. Anytime after May 1.

**Comment by dlindahl** [comment]
@devonbl @mjackson Maybe June would work better? That would give us all enough time to work out scheduling as well as allow me time to find a venue.

**Comment by dlindahl** [comment]
@devonbl Would you be available to do this React Workshop on Tuesday, June 23rd at 7pm?

**Comment by devonbl** [comment]
Noooooooooooooo

**Comment by dlindahl** [comment]
lol

What about Tuesday, July 28th at 7pm? :grinning:

**Comment by devonbl** [comment]
I have Netflix meetup that week.

**Comment by dlindahl** [comment]
We have just been approved a recurring date of the 4th Tuesday of every month. Does that conflict with a recurring date on your end? If so, then maybe I can work something out on a weekend instead of a weekday. 

My preference is to get something on the schedule sooner rather than later. Everyone at our meetups has expressed a strong desire to get hands-on with React and a ReactJS meetup has just been created. So I'd like to get something underway to help them get off the ground. Plus, I'd love to have your help with that given your experience! 

Are there any weekends that you are available in June?

**Comment by dlindahl** [comment]
@devonbl: I reached out for help from Tom Occhino who put me in touch with Steven Luscher from the Instagram team and he has offered to run the workshop for us. I wanted to sincerely thank you for offering to help us out with this!

Even though we couldn't get our schedules to work out, if you happen to be free when we get a date locked in for this (sometime in July), we would **_love_** to still have you come out in any capacity you'd like.

In addition, you have a standing invitation to come speak at a future SacJS event. We also have a new React-specific usergroup here in Sacramento started by Eve Porcello that is also looking for speakers that would also love to have you over!

Again, thank you **SO** much for offering your support. I really appreciate it and if there is anything we can do to help you or ReactSF out, please let us know!
