### ISSUE TITLE
Talk Proposal: Making Tool Management Disappear with Volta

### ISSUE THREAD

**Issue by charlespierce** [sacjs/sacjs.github.io#143]
Name: Charles Pierce

Twitter Handle: [@chuckapierce](https://twitter.com/chuckapierce)

GitHub Username: @charlespierce

Employer: LinkedIn

Talk Length: 30 mins

---

**Title**: Making Tool Management Disappear with Volta

**Brief Description**: Have you ever wasted hours chasing a mysterious bug instead of the actual work you had planned, only to discover you were using the wrong version of Node? Volta is a JS tool manager designed to solve just that problem: Launching the right tools for the project you’re working on so you can focus on building amazing JS applications.

In this talk, I will introduce Volta and discuss how it streamlines the development process for JS engineers. I’ll demonstrate how easy it is to get started with Volta and how it stays out of your way during development. I’ll also cover how we use Volta at LinkedIn on teams and projects of every size, from an internal tool with a few developers to hundreds of engineers building the flagship LinkedIn.com web app. Come learn how to make worries about tool versions a thing of the past!

**Comment by a-axton** [comment]
Hey @charlespierce, thank you for submitting! Are you available to give this talk at our next meetup on Tuesday Nov 26th?

**Comment by charlespierce** [comment]
Hi @a-axton! Yeah, I'm available and can definitely give this talk on the 26th :+1:
