### ISSUE TITLE
Zero to API in 30 minutes using NestJS

### ISSUE THREAD

**Issue by mpalmerlee** [sacjs/sacjs.github.io#147]
Name: Matt Palmerlee

Twitter Handle: https://twitter.com/mpalmerlee

GitHub Username: https://github.com/mpalmerlee

Employer: Encode Logic

Talk Length: 30 - 60 minutes

---

Title: Zero to API in 30 minutes using NestJS

Brief Description:
When building a new API using NodeJS you can go the a-la-carte route, piecing together an API using building block modules, or you can go with a framework that helps you get up and running quickly. In this talk I'll go over why I choose NestJS for a recent project and show how it can help you quickly get up and running with a new API using TypeScript, express, swagger, jest and other shiny new tools.

**Comment by a-axton** [comment]
Thanks for the last minute talk!
