### ISSUE TITLE
Talk Proposal: I am Ionic and So Can You

### ISSUE THREAD

**Issue by tnishimura** [sacjs/sacjs.github.io#149]
Name: Toshiro Nishimura

Twitter Handle:

GitHub Username: tnishimura

Employer: 

Talk Length: 30-40?

---

Title: I am Ionic and So Can You

Brief Description:
I will walk through creating a simple application with Ionic 4, all the way through creating a ready-to-publish android application. Along the way, I'll talk about the various pieces that make up Ionic and why I think it is worth your attention. 

Some Ideas I'll touch on:
- How Ionic is different from conventional frameworks like React and Angular
- Bootstrapping an application. 
- Cordova, as well as Ionic's newer 'Capacitor Project'
- How to use native features.
- Web components.
- Building and publishing.

**Comment by a-axton** [comment]
Hi @tnishimura! Are you available to give this talk on the 27th? Meetup was scheduled for Tue the 25th but I had to push it back a few days because I'm out of town

**Comment by tnishimura** [comment]
Hey @a-axton, yes, I can do it on the 27th if there are no other candidates. Tell me if there will be a second speaker so I can time my talk appropriately.

**Comment by a-axton** [comment]
Awesome, thank you! There are other proposals but we've been doing a lot of node stuff lately so I've been wanting to mix it up. I haven't accepted anyone else so you'll probably be the only one
