### ISSUE TITLE
Intro to NodeJS

### ISSUE THREAD

**Issue by dlindahl** [sacjs/sacjs.github.io#16]
@jeffprandall reached out to me via Meetup to let me know that @CrabDude was interested in coming up from Mountain View to a meetup to give a talk, possibly about NodeJS. This issue is about moving the conversation here and coordinating the details.

Adam, I understand you are likely unavailable for our April meetup and, as of now, our May meetup is booked up by a [Book Release Party](https://github.com/sacjs/sacjs.github.io/issues/5). Are you available in June?

**Comment by CrabDude** [comment]
Yup. I can do that. =) Anything in particular you guys would like me to
talk on? Any popular topics ATM?

One thing I'm enjoying at the moment is babel + eslint with async/await
support. A common demo I use to demonstrate this is a recursive ls
implementation.

Would that be a good fit?

Cheers,
Adam

**Comment by dlindahl** [comment]
While I personally would like to see that talk, I'm thinking it might be a touch advanced for our typical attendee. We just had an Intro to ES6 talk and ~90% had never seen ES6 code before. Additionally, only a couple people had even heard of Promises. So babel and `await` might be overshooting.

I'm thinking maybe a hands-on class might work better. Assuming a pre-requisite that everyone comes with Node installed, hand hold them through firing up a web server, then show them how to install a module (like Express or something else relatively easy to grok) and then serve out files or content. It might also be a good way to introduce Promises. Once they have written some callbacks and then transform those into promises, then that may segue nicely into a brief demonstration of the ES7 `await` syntax to close out the talk. How do you feel about something like that?

**Comment by samt** [comment]
If you wanted to do the workshop, I can assist people who are totally lost get up and running or help fix some system/user-specific problems they might encounter.

**Comment by CrabDude** [comment]
Let's table this for now. I'm currently working on some training material
that would be perfectly in line with what you're suggesting. Let's chat
again in a month.

**Comment by dlindahl** [comment]
@CrabDude Just a friendly ping so you don't forget about us :smiley: 

We are booked in May but should have open slots for meetups starting again in June. Any ideas what your schedule might look like?

**Comment by CrabDude** [comment]
My wife and I decided to go to Hawaii in June, so I'm free Mon 6/1 & Wed
6/3, but then not till after 6/20.

Cheers,
Adam

On Sun, Apr 26, 2015 at 6:29 PM, Derek Lindahl <notifications@github.com>
wrote:

> @CrabDude <https://github.com/CrabDude> Just a friendly ping so you don't
> forget about us [image: :smiley:]
>
> We are booked in May but should have open slots for meetups starting again
> in June. Any ideas what your schedule might look like?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sacjs/sacjs.github.io/issues/16#issuecomment-96458097>
> .
>



-- 
Adam Crabtree
Noderiety
PO Box 3823
Los Altos, CA 94024
Telephone: *(*469) 777-8415 <https://mail.google.com/>
Email: dude@noderiety.com

This e-mail message is intended for the use of the addressee(s) only and
may contain information that is privileged-confidential and exempt from
disclosure under applicable law.  If the reader of the message is not the
intended recipient or agent responsible for delivering the message to the
intended recipient, you are hereby notified that any review, dissemination,
distribution or copying of this communication is strictly prohibited.  If
you receive this communication in error, please notify us immediately by
reply e-mail and delete the original message.  Thank you.

**Comment by dlindahl** [comment]
Aloha! :palm_tree: :sunrise: 

I think we'll tentatively pencil this in for sometime in July. That's pretty far out for us right now, so things may change before then. We'll keep you in the loop.

Thanks again for offering to do this!
