### ISSUE TITLE
Sequelize with NodeJS

### ISSUE THREAD

**Issue by jeffprandall** [sacjs/sacjs.github.io#17]
@dlindahl is there anyone in the group who has any experience with Sequelize?  I am having some issues using Class Associations and was hoping I could pick someones brain.

**Comment by dlindahl** [comment]
I do not specifically nor am I aware of anyone, but I am fairly familiar with Rails and they look similar. You can either describe the problem you are having here and I can try to help, or you can come out on Wednesday and maybe find someone there that can help after the talks are over. A few people tend to hangout afterwards and I'm sure someone would be willing to at least [Rubber Duck](http://en.wikipedia.org/wiki/Rubber_duck_debugging) with you, myself included.

**Comment by jeffprandall** [comment]
I'll wait until the meeting to show you the spaghetti I have created.

**Comment by dlindahl** [comment]
:ramen: :grinning:
