### ISSUE TITLE
April Meetup Agenda

### ISSUE THREAD

**Issue by dlindahl** [sacjs/sacjs.github.io#18]
**Date:** April 29th
**Time:** 7pm
**Location:** The Urban Hive
**Meetup Url:** http://www.meetup.com/The-Sacramento-Javascript-Meetup/events/221914716/

* * *

##### 6:30pm Preparation

* Get space setup (chairs, projector, etc.)

##### 7:00pm Start

* Opening remarks (thanks for coming, CoC, introduce staff, etc.)

##### 7:15pm First Talk - Malte Ubl (@cramforce) (@google) (#19)

* Tradeoffs in server side and client side rendering

##### 7:45pm 30 minutes of staring silently at one another

* :eyes: 

##### 8:15pm Finish

* Sponsors

  * Thank Rocket Department for sponsoring the beverages

  * Thank Chelsea from TEKsystems for the food and introduce her to attendees

    Chelsea gets a 2-minute speaking slot as compensation for her sponsorship

* Give aways

  * O'Reily give away (@samt)

  * Give away Nomad+JS tickets (@dlindahl)

    Two free tickets to the [May 19th virtual meetup](https://nomadjavascript.com/may-2015/) entitled "Don’t Forget the Bug Spray: Debugging JavaScript" by Ryan Niemeyer. All we need is full name and email address which will be forwarded to the Nomad+JS staff for registration.

* Next meetup in May (Date TBD)

  Book Release Party! :tada: 

* Announce BeerJS and CoffeeJS sub-events

  Next BeerJS is May 6 (beerjs/sac#14)

  Watch Twitter (@sac_js & @beerjs_sac) or Meetup.com for news

* 15-seconds of fame

  Open the floor to attendees to make any announcements or comments that they have.

* Encourage post-event mingling

**Comment by samt** [comment]
Am I going to be doing a boring talk on UTF-8?

**Comment by dlindahl** [comment]
Always be prepared! Besides, if the talk is boring, that's on you, not the topic :wink: I would love to see a hilariously engaging talk about UTF-8 :grinning:

**Comment by samt** [comment]
I'll have it ready!

**Comment by dlindahl** [comment]
Ok, I was unable to secure a second speaker, so in the words of Bill O'Reilly, we're doing it live!

[![We're doing it live!](http://media.giphy.com/media/A34x7CEKUkCyc/giphy.gif)](http://www.youtube.com/watch?v=O_HyZ5aW76c)

@samt Since we do have one speaker, I think I want to bank your UTF-8 talk in the event we come up completely empty one month. I also have a talk I can create on linting when we get that desperate. So I think you are still off the hook for now.

If anyone has any creative ideas on how to fill the gap, I'm open to them. I'm hoping that since we have 35 RSVPs ( :astonished: ) that there will likely be some good QA time, but its worth being prepared otherwise. Worst case, Malte gets 30-45 mins of talk time and we start mingling early. :beers:

**Comment by samt** [comment]
:+1:

**Comment by cramforce** [comment]
I'm known to be on the fast side. I guess I will have to stretch things out :)

**Comment by dlindahl** [comment]
@cramforce I just had a brilliant idea: Present *two* talks! :wink:

**Comment by dlindahl** [comment]
@cramforce When do you expect to arrive? If you want to grab some food beforehand, let me know. We are working on a sponsorship that may or may not be providing some light food during, but I wouldn't bet your hunger on it.

**Comment by dlindahl** [comment]
@samt Rocket Department is picking up the tab for beverages (up to $50). I'll leave it up to you how you want to handle that with @efletch. Since you seem to have a system that has been working well for you, I would recommend sticking with that and save the receipt so that you can be reimbursed.

@a-axton We have 41 people coming :astonished:. We're probably going to need to pull out the extra chairs. Shouldn't be a big deal, but I wanted to make a note of it so that we're all prepared. Also, Malte will be up early to get some work done and have some dinner before 6:30pm. Is it OK if he crashes your office?

**Comment by samt** [comment]
Thanks @cramforce for giving your talk, we had great feedback from it!
