### ISSUE TITLE
The Psychology of Responsibility

### ISSUE THREAD

**Issue by dlindahl** [sacjs/sacjs.github.io#20]
[C. J. Silverio](https://twitter.com/ceejbot) of NPM expressed an idea about presenting on the "psychological changes that happen when you're handed responsibility for something."

I reached out to see if she'd like to present it at SacJS. The talk isn't quite written yet, but there is a chance it could get it done in time for the April meetup. If not, I extended an open invite for any future meetup.

---

https://twitter.com/ceejbot/status/577608673725415424

**Comment by samt** [comment]
That sounds like a totally awesome talk! Would love to have her :+1:

**Comment by dlindahl** [comment]
Unfortunately, CJ was unable to make April work, but she is definitely interested in a future date. She specifically asked us to keep bugging her :smile: 

* * *

https://twitter.com/ceejbot/status/590651206059630593
