### ISSUE TITLE
NomadJS Movie Night

### ISSUE THREAD

**Issue by dlindahl** [sacjs/sacjs.github.io#26]
@jakerella from NomadJS has offered us rights to show a NomadJS video at one of our meetups:

> Hi Derek!

> We were wondering if SacJS wanted to use one of the NomadJS videos as the main talk for one of your meetings. We'd give you the rights to show the video to the group at no cost, we'd just slap a logo on the video and maybe redo the intro to be more generic for you.

> I was thinking either John K Paul's talk on ES6 (https://nomadjavascript.com/product/es6-right-now/) or Margaret Leibovic's talk on async workflows with generators (https://nomadjavascript.com/product/asynchronous-js-with-yield/).

> Let me know what you think!

> --Jordan

I am definitely interested in doing this as a Movie Night :movie_camera: at The Hive.

At this point, its just a matter of scheduling. We've got quite a few speakers in the bank so I'm not entirely sure at this point where to slot it in. We'd likely know more after our May meetup how things will start looking into June.

@jakerella out of curiosity, were you looking at doing this as a gift to local user groups, or was there a time-sensitive advertising component to your offering? If you are trying to create buzz to increase NomadJS memberships, then that will guide how we'd schedule this (sooner rather than later). If there is no rush, then we can take a more considered approach to planning and execution. Either way, looking forward to this! :+1:

**Comment by samt** [comment]
That would be totally awesome!

**Comment by jakerella** [comment]
It is a gift. :)
But yes, it is also intended to be a marketing tool to drive membership. I'd probably record a custom intro for you folks to introduce NomadJS and send you all some stickers.

If you can fit it in June or July that would be great. We're trying some new things to keep the attendance up on the meetings (which has been okay, but not growing much). Obviously I don't want to cause any big rescheduling, so it's totally up to you folks!
