### ISSUE TITLE
May Meetup Agenda

### ISSUE THREAD

**Issue by dlindahl** [sacjs/sacjs.github.io#29]
**Date:** May 26th
**Time:** 7pm
**Location:** The Urban Hive
**Meetup Url:** http://www.meetup.com/The-Sacramento-Javascript-Meetup/events/222516756/

* * *

##### 6:30pm Preparation

* Get space setup (chairs, projector, etc.)

##### 7:00pm Start

* Opening remarks (thanks for coming, CoC, introduce staff, etc.)

##### 7:15pm First Talk - Chris Minnick (@chrisminnick) (@WatzThisCo) (#5)

* TBD

##### 7:45pm Second Talk - Eva Holland 

* TBD

##### 8:15pm Finish

* 15-seconds of fame

  Open the floor to attendees to make any announcements or comments that they have.

* Sponsors

  * Thank Rocket Department for sponsoring the beverages

  * Thank Chelsea from TEKsystems for the food and introduce her to attendees

    Chelsea gets a 2-minute speaking slot as compensation for her sponsorship

* Give aways

  * O'Reily give away (@samt)

  * Give away Nomad+JS tickets (@samt)

    Two free tickets to the [June 16th virtual meetup](https://nomadjavascript.com/june-2015/) entitled "Wrangling Transpilations" by Kyle Simpson (@getify). All we need is full name and email address which will be forwarded to the Nomad+JS staff for registration.

* Next meetup June 23rd

  TBD

* Announce BeerJS and CoffeeJS sub-events

  Next BeerJS is TBD

  Watch Twitter (@sac_js & @beerjs_sac) or Meetup.com for news

* Encourage post-event mingling

**Comment by dlindahl** [comment]
@samt I created a slide deck for you at https://github.com/sacjs/slides/tree/master/2015/05

You'll need to download and install the fonts at https://github.com/sacjs/assets/tree/master/fonts

Feel free to edit the deck as needed. The only thing that I ask you to keep in place in its entirety is the Code of Conduct.

Let me know if you have any problems!

**Comment by samt** [comment]
Everything went well! had to take off early due to family emergency, but @a-axton offered to do the clean up. Luckily we didn't have to move seats around this time because the presentations were short and it was more a party.
