### ISSUE TITLE
TBD?

### ISSUE THREAD

**Issue by dlindahl** [sacjs/sacjs.github.io#3]
I've convinced Google engineer and JSConf EU organizer Malte Ubl to come talk. Details TBD.

**Comment by dlindahl** [comment]
@a-axton said that Brandon has a spot open on either 2/18 or 2/25. He is waiting to hear back from another group before locking the date in. Right now, its looking like the 25th, so I'll pencil it in for then.

I'd also like to see if we can get a 2nd speaker, preferably local, for this meet-up that will help extend the meetup as well as act as a fall back if I can't get the scheduling to work out with Malte.

**Comment by dlindahl** [comment]
@a-axton Have you had a chance to chat with Brandon yet?

**Comment by dlindahl** [comment]
I will be talking with Malte this weekend in Tahoe and hope to get a more concrete idea for the meetup. In  general, I'd like to keep talks relatively short, so maybe I can convince him to bring some co-workers and maybe we can have a general theme for the night. I'll keep everyone posted.

**Comment by dlindahl** [comment]
I have confirmed with Malte that he will be speaking on the 25th @ 7pm. He is still deciding on a topic to present, but it will most likely be about server-side rendering.

**Comment by dlindahl** [comment]
Unfortunately, Malte had to cancel due to a deployment at Google :disappointed: and needs to reschedule. So we'll have to pivot. Anyone have any ideas? I'll try to work some leads, but any help would be appreciated.

**Comment by samt** [comment]
I could give a talk about something! Might be a bit higher level, but I could explain Unicode and UTF-8 as it relates to the web.

**Comment by samt** [comment]
@dlindahl I ran into Mike Machato at Hacker Lab yesterday during their anniversary party, he said he mentioned to you someone who would be interested in talking. He's spoken at OSCON before and has some good JavaScript content. Do you know anything else about that?

**Comment by dlindahl** [comment]
If that conversation was at BeerJS, anything is possible :dancer: 

Carson Gross reached out to me offering to talk about intercooler.js. He's a local dev and a couple of our attendees work with him. I believe he's known in SacRuby.

I'd like to have 3 speakers, so @samt, if you have a talk lined up about JS and UTF, then I think that'd be a great way to round out the evening. We'd have 20mins slots for 3 speakers, 30mins for 2 (obviously)

**Comment by dlindahl** [comment]
@a-axton Also, just to triple check, we are still good for The Hive on the 25th @ 7pm, right?

**Comment by dlindahl** [comment]
@samt I put you on the schedule as a Plan B. I'm trying to get someone from NPM up. So be on stand by. I definitely want to hear your talk, cuz UTF-8 is amazingly weird. We might highlight it in March though. Just wanted to give you a heads up.

Also, if you can get the OSCON person's info, that'd be great. We can get the ball rolling on future meetups that way.

**Comment by dlindahl** [comment]
I'm closing this in favor of #11
