### ISSUE TITLE
VR Evangelist @ Microsoft, Liv Erickson

### ISSUE THREAD

**Issue by dlindahl** [sacjs/sacjs.github.io#30]
I pinged @misslivirose about the possibility of coming to Sacramento and talking to us about VR, WebVR, the Web, Microsoft and/or anything else she wanted to talk about and she agreed! This will serve as the official thread to discuss logistics, etc.

We meet at The Urban Hive on the 4th Tuesday of every month at 7pm. We try to plan for three 20-min, two 30-min, or one 45-min presentation depending on how many other speakers we have.

As of right now, I think our July 28th meetup would be best, but I might want to move you up to our June 23rd meetup if our current plans fall through. Do those dates work for you? Got any questions for us?

Thanks Liv!

**Comment by misslivirose** [comment]
Hey there! 

I'd love to come up and do a talk on VR - I think something similar to what I did at last week's JSConf would be a lot of fun: a general overview of the VR ecosystem, talking about what I've worked on with WebVR and the web's role in virtual reality, showing off some examples, and helping give an overview of how people can get started building their own VR apps! Depending on the size group that you normally get, I can also see about bringing up a few mobile headsets to get people hands-on. It generally works best with smaller groups but depending on the demo I can do something shorter to give more people the chance to see the Oculus in action if they've never used it before. 

I can tailor the talk to whatever time frame works best for you - a 45 minute talk would likely be best as it allows a good amount of time for showing some examples, doing a Q&A, and walking through the code a bit, but it can definitely be shorter as needed. Both of those dates currently work for me, so either one would be fine.

Thank you!

**Comment by dlindahl** [comment]
Uh... that sounds epic!

We are a relatively new meetup but our numbers are growing quickly. I'd say to expect somewhere between 20-30 attendees. If you are most comfortable with a solid 45-min talk with examples, Q&A, and some Oculus time, I think that would be perfect. After the official meetup is over, about half the group usually hangs around afterward for some mingling and additional Q&A time. That might allow for some additional Oculus time that people want to have.

In the off chance I have to move you up on the schedule to June, how much advance notice would you need?

**Comment by misslivirose** [comment]
Awesome, the format sounds great then! I can plan on doing that and if anything changes just let me know. If June ends up working better for you, I should be good as long as I get 5-7 days notice. Most of the talk is already prepped, so it would just be scheduling the drive up. 

Thanks!

**Comment by dlindahl** [comment]
@misslivirose I'm still working on confirmation, but its looking more and more likely that we'll be moving your presentation up to our June 23rd meetup. Just wanted to give you a heads up. I'll let you know once things locked in! :blush:

**Comment by misslivirose** [comment]
Sounds great, let me know when it's finalized! :)

**Comment by dlindahl** [comment]
@misslivirose I'm going to go ahead and lock you in for the 23rd. Is that good for you?

**Comment by misslivirose** [comment]
Yep, sounds good!

**Comment by dlindahl** [comment]
:tada: :100: :+1: :smile:

**Comment by dlindahl** [comment]
@misslivirose: Do you have a title and/or an abstract that I can use to promote the event? Doesn't have to be perfect, just helps create the announcement and my opening slides.

**Comment by misslivirose** [comment]
Yep!

Feel free to let me know if there's something else you'd like me to pull in or include, I'm using this as a reference:

Title: JavaScript for Virtual Reality

Abstract: Is 2015 the year of Virtual Reality? Experts suggest that VR will be a 150 B industry by 2020 - but right now, the majority of VR development tools require heavy game engines and specialized desktops. In this talk, we'll discuss the emerging support from the VR and web communities for WebVR, a new API emerging to support writing VR-enabled websites using HTML, CSS, and JavaScript. We'll be taking a look at existing applications for virtual reality on the web, the benefits of WebVR, and how to get started with the available tools and libraries for browser-based virtual reality written in JavaScript.

**Comment by dlindahl** [comment]
![](https://newarray00.files.wordpress.com/2014/05/shut-up-and-take-my-money-9299-2560x16001.jpg)

It sounds awesome! I'm so excited!

**Comment by misslivirose** [comment]
I'm so glad! I've got everything blocked out on my calendar, can't wait!

**Comment by dlindahl** [comment]
@misslivirose Do you have any questions for us before you hit the road?

We usually start setting up at 6:30pm and kick-off the evening sometime around 7pm (once the stragglers get settled). One of our sponsors should be providing some :pizza: and we'll have water, :beer:, and soda on hand. You're the only speaker so if you run a bit long, it won't be a problem.

If you need a specific projector adapter, please let us know ASAP so we can make sure we have you covered.

The meetup space is located at:

The Urban Hive
1931 H St
Sacramento, CA 95811
[Map](https://www.google.com/maps/place/The+Urban+Hive/@38.579196,-121.479038,17z/data=!3m1!4b1!4m2!3m1!1s0x809ad0c545052faf:0x765f4cd286fb0959)

Street parking is available anywhere around H and 20th, and all parking restrictions should lift after 6pm. Just be mindful of any parking signs!

If you have any questions or need help with anything, feel free to respond here, tweet at me @oif_vet or @sac_js, or call/text me at 703-328-4703

Thanks for coming and we're looking forward to tonight!

**Comment by misslivirose** [comment]
Hi! I would need a lightning adapter (mini display port) for my Macbook Pro since the Oculus uses the HDMI port. I'm excited! I'll let you know if I run into anything on my way up there (on the way now, so hopefully traffic cooperates!)
