### ISSUE TITLE
ReactJS Workshop Budget

### ISSUE THREAD

**Issue by dlindahl** [sacjs/sacjs.github.io#34]
This constitutes a rough budget for the workshop (#31).

The goal here is to ensure that the balance is exactly $0.

| Item | Cost | Who |
|--------|-------|--------|
| Ticket Revenue | $305.03 | Tito @dlindahl |
| Sponsorship | $800.00 | Autodesk @samt |
| Venue Rental | ($180.00) | @samt |
| Breakfast ($109.99 per 20pp + tax) | ($230.98)  | @dlindahl |
| Snacks, Beverages | ($76.28)  | Costco @dlindahl |
| Beverages | ($15.00)  | Raley's @dlindahl |
| Chipotle ($13.50pp + tax) | ($615.20) | @samt |
|--------|-------|--------|
| Balance | ($-12.43) | |

All receipts should be attached as images to this issue.

**Comment by dlindahl** [comment]
![noahs bagels](https://cloud.githubusercontent.com/assets/55945/8729748/d9e492a0-2ba1-11e5-8e0d-dabe3c44f968.png)
![noahs bagels 2](https://cloud.githubusercontent.com/assets/55945/8729781/fd85da98-2ba1-11e5-9dd2-0b182d406f80.png)

**Comment by samt** [comment]
![chipotle_order_july18](https://cloud.githubusercontent.com/assets/150040/8729803/2154bb38-2ba2-11e5-837a-928ddd1f4ae6.png)

**Comment by dlindahl** [comment]
![costco](https://cloud.githubusercontent.com/assets/55945/8992491/98840954-36b3-11e5-8097-73ac999d3a0d.jpeg)

This receipt contains two un-reimbursable items. The actual total should be as follows:

|  |  |
|--------|-------|
| Sub-total | $70.30 |
| Tax | $5.98 |
| Total | $76.28 |

**Comment by dlindahl** [comment]
![raleys](https://cloud.githubusercontent.com/assets/55945/8992557/04eea5fe-36b4-11e5-9aea-48b5d8b99dd7.jpeg)

**Comment by dlindahl** [comment]
@samt Looks like I went over budget by just a teeny amount. I'll take the hit so just short me on the reimbursement whenever we get to it.

**Comment by dlindahl** [comment]
I have no idea where we stand on this anymore so I'm just going to say everything is settled and close it out :dancer:
