### ISSUE TITLE
Alex Russell, Google Chrome/Dev Relations

### ISSUE THREAD

**Issue by dlindahl** [sacjs/sacjs.github.io#35]
At TXJS, @slightlyoff volunteered to come talk at a future meetup. Given his understandably busy schedule, the best we could come up with was November 24th.

After looking at the calendar, we might want to push that back even further since that is only 2 days before Thanksgiving. In fact, I might not even be in town for that meetup. If we decide to move it back, our calendar is pretty clear for any future Fourth Tuesday:

* February 23
* March 22
* April 26
* May 24
* June 28
* July 26

Alternatively, I can check with our venue and see about maybe moving our meetup to an earlier Tuesday. @slightlyoff, if there is a particular Tuesday that works best for you, that will help us coordinate with our venue.

Thanks again for offering to come speak! We're looking forward to it!

**Comment by slightlyoff** [comment]
Is feb 23 still open?

**Comment by dlindahl** [comment]
@slightlyoff Yes it is! Want to lock it in?

**Comment by dlindahl** [comment]
Hey @slightlyoff, February will be here before we know it and I wanted to ping you to make sure that we're good to go for you to come up on the 23rd. All I need from you is a :100: on your ability to make it, a talk title, a talk length, and a sentence or two of an abstract for our meetup announcement.

Thanks!
