### ISSUE TITLE
CoffeeJS September

### ISSUE THREAD

**Issue by a-axton** [sacjs/sacjs.github.io#36]
Let's plan another CoffeeJS! I'll be busy the weekend of the 8th and 15th so I was thinking maybe the 22nd/23rd? Although, that might be a little too close to our regular meetup.

Possible locations
1. Naked Lounge, 11th and H
2. Temple, 28th and S (large outside area)

**Comment by dlindahl** [comment]
I'm available on the 15th, so I'd be down for that

**Comment by samt** [comment]
15th is good here :+1: Hopefully the weather will be kind to us that morning should we opt for S street Temple.

**Comment by a-axton** [comment]
I was trying to get a date that I could make, but ya the 15th makes more sense timing wise.

**Comment by dlindahl** [comment]
Haha I totally misread your email...

The 22nd or 23rd can work, but we do have a meetup on the 25th. I'd also be OK going with something in early September and have the date locked in so we can promote it properly at the meetup.

**Comment by dlindahl** [comment]
So I dropped the ball on this one.

How does Saturday, September 26th sound?

**Comment by samt** [comment]
I can be there!

**Comment by dlindahl** [comment]
I'm assuming the weather will be nice by then. Want to do it at Temple on 28th and S?

**Comment by dlindahl** [comment]
I'll be announcing CoffeeJS at Temple this Saturday the 26th at tonight's meetup, so clear your calendars :smile:

**Comment by dlindahl** [comment]
Moved to beerjs/sac#16
