### ISSUE TITLE
Property based testing

### ISSUE THREAD

**Issue by joneshf** [sacjs/sacjs.github.io#37]
Per: https://twitter.com/sac_js/status/629009116946661376 

I'd like to present a talk about property based testing (PBT), where the idea is to test generalized properties or laws about a program, rather than specific instances.

Depending on how much time, I'd like to touch on:
* What is testing?
* Why is it important?
* Things testing cannot do.
* Drawbacks of example based testing.
* History of PBT.
* Benefits of PBT.
* How to use PBT in JS.
* Simple example.
* Intermediate/real-world example.
* Advanced example.

How does that sound?

**Comment by joneshf** [comment]
Thoughts, comments, suggestions?

**Comment by dlindahl** [comment]
Sorry for the late response, I was out of town for the week and am just now getting caught up.

I think this talk sounds great! In fact, I've never even heard of PBT before now, so I think this will make for quite an interesting talk.

As of right now, we have one other speaker penciled in on 8/25 so please plan on providing 30-minutes of content. Is that enough to cover all the topics you'd like?

**Comment by joneshf** [comment]
No worries. I didn't mean to sound impatient.

Yeah, 30 min should be just fine. Thanks.
