### ISSUE TITLE
A JS Noob’s Experience Learning D3

### ISSUE THREAD

**Issue by DigitalSplashMedia** [sacjs/sacjs.github.io#38]
Derek  asked if I would be available to talk about my experiences with the data and D3. Absolutely, but it would help me to know:

How long to expect to talk
What format it should be (presentation with slides, informal chat, go through code...?)
Anything in particular anyone would like to hear about D3 and data visualization.

**Comment by dlindahl** [comment]
* Plan on presenting for 30-minutes
* Format is entirely up to you!

  Personally, I think a presentation with slides is easier to digest for attendees. Feel free to allow time for Q&A in your block of time. We also encourage attendees to hang out afterwards to continue the conversation.

* I think an explanation of what D3 is, how it differs from other charting/viz libraries, and some personal anecdotes about a problem you personally ran into that D3 solved would be a good place to start

The meetup is on 8/25 at The Urban Hive in Midtown. We start at 7:00pm and there will be one other speaker that night. Let us know if you need anything else! I personally will be out of town that night, but our co-organizers @samt and @a-axton can help you with anything you need the day of.
