### ISSUE TITLE
Functional Programming in JavaScript

### ISSUE THREAD

**Issue by Bradcomp** [sacjs/sacjs.github.io#40]
We talked a bit last night about my doing a talk on using functional programming techniques in JS.

I would be interested in doing this if other people are interested.  

I would want to talk about some combination of the following, depending on interest:
* What is FP and why we should care
* Function purity and side effects
* First class functions & lambdas
* Currying and partial application
* Lists and list processing (map, filter, folds, etc.)
* Higher order functions and function composition
* Lazy evaluation
* Tools and libraries

I would give real world examples and keep it practical, focusing on how these techniques can make our lives easier as programmers.

**Comment by a-axton** [comment]
Awesome, I'm glad you submitted this! Are you thinking about having this for our next meetup or another future one?

**Comment by Bradcomp** [comment]
Is the next meetup the 22nd of September?  I can do that. I could also do October if that works better.

**Comment by samt** [comment]
AFAIK, we don't have any speakers lined up for September, not sure if @dlindahl had any leads yet.

This sounds awesome! I love the focus on practicality with this (it's a lot more approachable given our wildly diversified group of people).

**Comment by Bradcomp** [comment]
I can totally do this for September if there is nothing else lined up.  

Should I plan for like 45 minutes to an hour?

**Comment by dlindahl** [comment]
Sorry for the delay, I'm super slammed right now.

We have one lead, but he's not confirmed yet. This is definitely going on the schedule though. I'll get back to you with a talk length as soon as I can! For now, plan on _at least_ a 20mins of material for right now.

**Comment by dlindahl** [comment]
@Bradcomp I haven't heard back from the other potential speaker so it looks like its going to be a one person show! Would you like to do 30mins or 45min? You can have as much as you like, I just need to know for scheduling purposes. Thanks for volunteering to speak!

**Comment by Bradcomp** [comment]
I can do 45 minutes.

**Comment by Bradcomp** [comment]
@dlindahl What sort of set up do you have as far as projector, etc?

**Comment by samt** [comment]
There is a projector and hookups for both Thunderbolt/Display port and VGA.

**Comment by dlindahl** [comment]
Scheduled! http://www.meetup.com/The-Sacramento-Javascript-Meetup/events/225424247/

@Bradcomp Are you on Twitter at all?

**Comment by Bradcomp** [comment]
@dlindahl Yes I'm @notpmoc84.  Rarely on there though.

**Comment by Bradcomp** [comment]
@samt Mini VGA or regular 15 pin?  No HDMI?

**Comment by dlindahl** [comment]
I believe the projector is native HDMI. It includes an adapter to convert it to Thunderbolt. So it can support both.

**Comment by joneshf** [comment]
Woo! This is awesome!

**Comment by dlindahl** [comment]
Once again @Bradcomp, you did a great job last night! Let us know when you're free to present again! :smile:
