### ISSUE TITLE
Memory Leaks in JS Apps

### ISSUE THREAD

**Issue by samt** [sacjs/sacjs.github.io#45]
Estimated Length: **20 mins**.

Topics:

* What is a memory leak?
    * Memory and V8 (chrome/node.js)
    * Why does it happen?
    * Where does it happen? (closures, et. al.)
* Identify Leaks
    * Using observation
    * Using tools
* Fixing memory leaks
    * As they are spotted
    * Before they happen (best practices/patterns)

------

This presentation is a work in progress and doesn't dive terribly deep, think of it as more of an awareness  campaign. :smile:

**Comment by dlindahl** [comment]
Let's do this talk in December as a warm-up to Lightning Talks. Sound good?

**Comment by samt** [comment]
Awesome :+1:

**Comment by samt** [comment]
Let's hope I can remember this. ( :stuck_out_tongue:  )

**Comment by samt** [comment]
I am going to table this particular 20 min talk for a later date.

**Comment by dlindahl** [comment]
@samt Our speakers for Jan appear to have fallen through. Any chance you could give this on the 26th?

**Comment by samt** [comment]
I will have it ready for the 26th.
