### ISSUE TITLE
You don’t need JavaScript for that!

### ISSUE THREAD

**Issue by benmvp** [sacjs/sacjs.github.io#46]
We have been using JavaScript toolkits like jQuery for nearly a decade to make manipulating the DOM easier as we create our highly-interactive web apps. New features in HTML5 & CSS3 should’ve made old development strategies obsolete, and yet we’re still using jQuery to do things better suited for HTML5 & CSS3. Why? Well, old habits die hard.

In this session, let’s look at ways we used to build interactivity in JavaScript and see how we can transform them into more optimal solutions using plain old HTML and CSS. We’ll discuss CSS3 transitions & animations, new HTML5 attributes, and other “tricks” to offload JavaScript functionality to the browser’s rendering engine for more performant web applications. Whether you’re a seasoned JavaScripter or just getting started, you’ll leave the session with fresh ideas to work with.

-----

**Estimated length:** 45 minutes

**Comment by dlindahl** [comment]
@benmvp: Wanted to check-in with you to make sure you are squared away with coming up tomorrow (directions, etc.). Let me know if you have any questions!

**Comment by benmvp** [comment]
I think I'm pretty good. Was just going to rely on Google Maps to get me there :smile: 

What time should I get there? 6:30P? 6:45P?

I have a universal dongle to connect to VGA, DVI & HDMI so I should be good in terms of projection. I also have set up the slides to not rely on Internet.

What's your feel for the experience level of those attending regarding the topic of HTML5 & CSS3?

**Comment by dlindahl** [comment]
We usually start setting up at 6:30 and people start showing up at 6:45

We may have a room change to deal with tomorrow so I'm going to get there a bit early to ensure we get it straightened out in time. Let me know when you plan on arriving and I'll make sure someone is there to meet you.

I'd say most attendees are fairly knowledgeable about HTML and CSS. Of the attendees that don't write JS all day, most tend to be Wordpress devs and freelancers. I'd guess most are familiar with SASS, but PostCSS is probably not as common.

Hope that helps! Let me know if you need anything else. We're excited to have you up!

**Comment by benmvp** [comment]
Ok, cool. Thanks for the info!

I plan to be there some time between 6:30 - 6:45 so I can have enough time to set up and test things out
