### ISSUE TITLE
Rusty Node

### ISSUE THREAD

**Issue by mfpiccolo** [sacjs/sacjs.github.io#48]
Systems programming is scary!  You can crash your server, create memory leaks, loose important data and a myriad of other bad things can happen if us high level programmers decided to start writing C code.  This is the main barrier of entry into this domain.  What if you could write code that gave you the power and speed of low level code while keeping you from many of the pitfalls that make low level code unsafe?  Well that is Rust my friend!

The Rust programming language is built in a way that the code will not compile unless it safe.  So with that worry out of the way now high level programmers, like javascript developers, can dip their feet into the systems programming world and see how the water feels.  

Why would you want to use Rust?  
For staters it has the ability to be really fast.  From benchmarksgame it is about 50 times faster than PHP, Ruby and Python and around 10 times faster then V8.  It is about 1.5 times slower than C which is super fast.
http://benchmarksgame.alioth.debian.org/u64q/which-programs-are-fastest.html

Second it also has the ability to have a very small memory footprint.  Rust compiles down to a binary executable which is automatically optimized to be low memory.  The language also has no garbage collection process so again saves memory.  Along with being low memory out of the gates the language has a lot of tooling that allows for low level optimizations much like C or C++.

So that probably all sounds cool but as a JavaScript developer, how are you supposed to use it?  Well, Node.js actually has a foreign function interface (FFI) which allows you to run Rust processes directly from node.  Its that simple.  Let's start using Rust!

**Comment by dlindahl** [comment]
@mfpiccolo Is this your full talk proposal, your lightning talk proposal, or both?

**Comment by mfpiccolo** [comment]
@dlindahl  This is the full talk.  When are the lightning talks?  I am sure I can boil it down to basically just the pitch part of the talk for a 5 minute talk.

**Comment by dlindahl** [comment]
I'm working on the schedule now. We're doing lightning talks on the 12/16. If you could open a separate Issue for the lightning talk version, that'd be great (preferably with a shorter "abstract" I can use on the website)

I'll leave this open so I can schedule it as a full talk in an upcoming meetup.
