### ISSUE TITLE
Coding with JavaScript For Dummies book release party

### ISSUE THREAD

**Issue by dlindahl** [sacjs/sacjs.github.io#5]
Chris Minnick has a new book, Coding with JavaScript For Dummies by Chris Minnick and Eva Holland, coming out and he said he'd be happy to give an intro course on web tech as part of a book release party.

**Comment by dlindahl** [comment]
@chrisminnick @sacjs/staff Looking for ideas for this little shindig. I've asked both New Helvetia and Yolo about getting event space. New Helvetia is a bit trickier since their space is smaller. But Yolo has plenty of space, including a private area, and were amenable to hosting an event. Additionally, any other restaurant or brewery would also work. Also, I'm sure Brandon @ The Hive would enjoy hosting the party.

@chrisminnick: Any chance the publisher can offer monetary support for food/beverage and some swag to hand out?

**Comment by chrisminnick** [comment]
Publishers don't like to spend money on marketing unless they see
significant numbers of pre-orders (hint hint!). I will ask! We'll have a
few copies of the book to give away at the event too.

Another location option would be The Trade (22 and K). They have a great
upstairs space where we're going to start doing the HTML5 meetups.

On Tue, Mar 10, 2015 at 11:58 PM, Derek Lindahl <notifications@github.com>
wrote:

> @chrisminnick <https://github.com/chrisminnick> @sacjs/staff
> <https://github.com/orgs/sacjs/teams/staff> Looking for ideas for this
> little shindig. I've asked both New Helvetia and Yolo about getting event
> space. New Helvetia is a bit trickier since their space is smaller. But
> Yolo has plenty of space, including a private area, and were amenable to
> hosting an event. Additionally, any other restaurant or brewery would also
> work. Also, I'm sure Brandon @ The Hive would enjoy hosting the party.
>
> @chrisminnick <https://github.com/chrisminnick>: Any chance the publisher
> can offer monetary support for food/beverage and some swag to hand out?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sacjs/sacjs.github.io/issues/5#issuecomment-78214194>.
>



-- 
Chris Minnick
http://about.me/chrisminnick
916-551-1453

Please Note our New Address!

PO Box 161393
Sacramento, Ca 95816

Instructor, Creating Mobile Apps with HTML5 (http://www.minnick.com/training
)
Instructor, Achieving Top Search Engine Placements (http://www.ed2go.com/)
Author, Beginning HTML5 and CSS3 for Dummies (Wiley, 2013)
Author, WebKit for Dummies (Wiley, 2012)

**Comment by dlindahl** [comment]
I'm generally OK with having it there, but I want to be sensitive to the fact that since The Trade is a co-working space and technically a competitor to The Hive, I don't want to cause any friction and end up losing our event space. We should probably discuss it with @sacjs/staff and see if they have any input.

Outside of the venue, here is a general agenda draft:

* Start with a maybe 30min "cocktail hour" for people to mingle and chit chat
* I can kick off the event and introduce Chris and Eva.
* Chris and Eva can both give a 20min talk on some aspect of JS, specifically as it relates to the book. Maybe walk through their favorite chapter?
* Close out with give aways or book sales
* Continue hanging out

If you want pre-sales, I can help promote the book through Twitter and Meetup. A link would help for that. And if you have a pre-sale copy, maybe you can bring it to the April meetup and we can close out the evening with a quick book promotion and announcement of the book release party.

Thoughts?

**Comment by chrisminnick** [comment]
We asked Wiley if they'd kick in some money for meetup sponsorship, and
they said no. They will be sending us some books (not sure when yet,
though) and some For Dummies stuff we can give away.

I think we can probably get a sponsor for drinks, however. We'll work on
that and let's discuss next week!

I'd love to do it at the Hive if it's available and I think we should!
Let's keep it simple - the hive is where you've been doing meetups, so
let's have it there!

I think your proposed plan sounds great! We'll discuss and get back to you
with more details when we can.

Here's the link to the book:
http://www.amazon.com/Coding-JavaScript-Dummies-Chris-Minnick/dp/1119056071

Any promotions you can help with would be awesome!

-Chris



On Thu, Mar 19, 2015 at 10:54 AM, Derek Lindahl <notifications@github.com>
wrote:

> I'm generally OK with having it there, but I want to be sensitive to the
> fact that since The Trade is a co-working space and technically a
> competitor to The Hive, I don't want to cause any friction and end up
> losing our event space. We should probably discuss it with @sacjs/staff
> <https://github.com/orgs/sacjs/teams/staff> and see if they have any
> input.
>
> Outside of the venue, here is a general agenda draft:
>
>    - Start with a maybe 30min "cocktail hour" for people to mingle and
>    chit chat
>    - I can kick off the event and introduce Chris and Eva.
>    - Chris and Eva can both give a 20min talk on some aspect of JS,
>    specifically as it relates to the book. Maybe walk through their favorite
>    chapter?
>    - Close out with give aways or book sales
>    - Continue hanging out
>
> If you want pre-sales, I can help promote the book through Twitter and
> Meetup. A link would help for that. And if you have a pre-sale copy, maybe
> you can bring it to the April meetup and we can close out the evening with
> a quick book promotion and announcement of the book release party.
>
> Thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sacjs/sacjs.github.io/issues/5#issuecomment-83693621>.
>



-- 
Chris Minnick
http://about.me/chrisminnick
916-551-1453

Please Note our New Address!

PO Box 161393
Sacramento, Ca 95816

Instructor, Creating Mobile Apps with HTML5 (http://www.minnick.com/training
)
Instructor, Achieving Top Search Engine Placements (http://www.ed2go.com/)
Author, Beginning HTML5 and CSS3 for Dummies (Wiley, 2013)
Author, WebKit for Dummies (Wiley, 2012)

**Comment by dlindahl** [comment]
:+1:

@a-axton When you are getting some dates from Brandon, can you ask if we can host this party at The Hive? All we need is his blessing and a date.

**Comment by dlindahl** [comment]
@samt You are available to run the meetup on the 26th, right?

**Comment by samt** [comment]
Yes

**Comment by dlindahl** [comment]
@samt Awesome. I'll prepare a basic slide deck in Keynote that you can use, modify, or completely disregard.

**Comment by chrisminnick** [comment]
Thanks guys! Let me know if you need us to do anything! Looking forward to it.
