### ISSUE TITLE
Lightning Talk: React Native

### ISSUE THREAD

**Issue by owenscott** [sacjs/sacjs.github.io#57]
Name: Owen Scott
Twitter Handle: @ownsctt
GitHub Username: owenscott
Employer: Open Town
Hometown: Ottawa (Canada)
Talk Length: 5 mins
---
Title: A First Foray Into React Native
Brief Description: A quick look at what React Native is, how it works, and how it's different from other javascript-to-native frameworks (e.g. Phonegap), told through the lens of someone stumbling through it for the first time :)

**Comment by MLichtenstern** [comment]
Name: Mariah Lichtenstern
Twitter Handle: lightedstar
GitHub Username: mlichtenstern
Employer: CINESHARES
Hometown: Oakland, CA
Talk Length: 5 minutes
---
Title: A New Era in Hollywood
Brief Description: CINESHARES is uniquely positioned to be the first Ecosystem as a Service to help EAAS filmmakers through the Hollywood labyrinth script-to-screen. Our patent-pending technology uses human-assisted AI to produce and distribute commercially viable films, while meeting the needs of investors and audiences that support them. Capitalizing on rising trends in independent film, crowd funding, and video on demand, we’re ushering in a new era in Hollywood.

**Comment by dlindahl** [comment]
@MLichtenstern To submit a talk, please open a new Issue. This helps us track each talk proposal individually
