### ISSUE TITLE
Promises Promises

### ISSUE THREAD

**Issue by Bradcomp** [sacjs/sacjs.github.io#59]
Name: Brad Compton
Twitter Handle: @notpmoc84
GitHub Username: Bradcomp
Employer: CLC Incorporated
Hometown: Sacramento
Talk Length: 30 minutes
---
Title:Promises? Promises!
Brief Description:  Promises can drastically improve the way we are writing our async code.  They give us back the ability to centralize our error handling and return values from functions like we can in synchronous code.  

We'll be going over what Promises are, what they can do, and how we can start using them.

If we have time, we will then take a look at the future async / await features that are making their way into the spec.

**Comment by dlindahl** [comment]
[![IMAGE ALT TEXT HERE](http://img.youtube.com/vi/H8Q83DPZy6E/0.jpg)](https://www.youtube.com/watch?v=H8Q83DPZy6E)
Naked Eyes - Promises Promises

**Comment by dlindahl** [comment]
Thanks for the submission! Depending on how March plays out, we'll likely get this on for April.

**Comment by dlindahl** [comment]
Hey @Bradcomp, our speakers for January seem to have fallen through. Would you be able to give this talk on the 26th?

**Comment by Bradcomp** [comment]
@dlindahl Sure! I can have something together for the 26th!

**Comment by dlindahl** [comment]
Awesome! Thanks for pitching in last minute!

**Comment by Bradcomp** [comment]
Minor quibble, but you have the wrong twitter handle up for me on the website.  Should be @notpmoc84

**Comment by dlindahl** [comment]
Yeah I caught that at some point... :smile: Sorry about that!
