### ISSUE TITLE
Hackathon

### ISSUE THREAD

**Issue by trusktr** [sacjs/sacjs.github.io#61]
How about a meetup during the live virtual Hack.Summit hackathon on Feb 20-21st? $150,000 in prizes. I think it'd be fun! hacksummit.org

**Comment by trusktr** [comment]
Maybe there can be a local prize for SacJS specifically? If interested, I'll help raise awareness.

**Comment by efletch** [comment]
I like the idea of doing a meetup around a virtual hackathon. Hack.Summit has already passed but maybe we could do a different one? 

[NASA Space Apps Challenge](https://2016.spaceappschallenge.org/) (April 21 - 22) was mentioned on the SacTech Slack a few days ago.

**Comment by trusktr** [comment]
@efletch Yeah, a hackathon in general would be awesome! It could even be a SacJS-specific hackthon. :D
