### ISSUE TITLE
Talk proposal: Using Redux with React

### ISSUE THREAD

**Issue by decafdennis** [sacjs/sacjs.github.io#65]
Name: Dennis Stevense
Twitter Handle: https://twitter.com/decafdennis
GitHub Username: https://github.com/decafdennis
Employer: Digital Deployment, Inc.
Hometown: Sacramento, CA
Talk Length: 20 mins (flexible)

Title: Using Redux with React
Brief Description: Introduction to React and Redux, and a demonstration of a tool we built using these and related libraries. (TBD)

**Comment by dlindahl** [comment]
@decafdennis Quick ping to confirm that you're still available to present on the 26th :smile:

**Comment by decafdennis** [comment]
@dlindahl Yes I am!

**Comment by dlindahl** [comment]
Thanks for submitting, we'll be officially announcing the lineup soon!
