### ISSUE TITLE
Talk Proposal: What's New In Intercooler.js

### ISSUE THREAD

**Issue by carsongross** [sacjs/sacjs.github.io#66]
Name: Carson Gross
Twitter Handle: carson_gross
GitHub Username: carsongross
Employer: LeadDyno
Hometown: Sacramento
Talk Length: 10 minutes
---
Title:  What's new in Intercooler.js
Brief Description:  The last time I talked about intercooler at SacJS I was at version 0.4.9.  We are now at v0.9.5, and a bunch of new features have dropped:

*  Pure CSS transition animations
*  AJAX history support rewrite
*  The ic-action attribute for pure client-side actions
*  Intercooler is now available via bower and CDNJS

I'll go over these, as well as some new examples using it, and talk a bit about when I plan on cutting a 1.0

**Comment by dlindahl** [comment]
Thanks for submitting, we'll be officially announcing the lineup soon!
