### ISSUE TITLE
Talk Proposal: Stateless Web Apps with Elm

### ISSUE THREAD

**Issue by daltonamitchell** [sacjs/sacjs.github.io#67]
Name: Dalton Mitchell
Twitter Handle: daltonamitchell
GitHub Username: daltonamitchell
Employer: Consolidated Fabricators
Hometown: Galt, CA
Talk Length: 10 mins
---
Title: Stateless Web Apps with Elm
Brief Description: I'll provide a brief introduction to Elm, a functional language that compiles to Javascript. I'll also talk about the benefits of immutability and the mindset shift that comes from debugging compiler errors vs in the console.

**Comment by Bradcomp** [comment]
👍

**Comment by dlindahl** [comment]
Thanks for submitting, we'll be officially announcing the lineup soon!
