### ISSUE TITLE
Talk Proposal: The Physical Web

### ISSUE THREAD

**Issue by a-axton** [sacjs/sacjs.github.io#68]
Title: What is the physical web?
Description: The physical web is a movement by Google to bring digital interaction with physical objects to the web browser. It consists of a standard bluetooth protocol and a few emerging web technologies such as the bluetooth web api. Google has already launched an initial implementation for Chrome on Android. I'll go over the basics of the technology, why it's important and some cool use cases.

Talk Duration: 10-30 mins depending on space needed to fill. If we need a full talk I can probably work in a demo too.

**Comment by efletch** [comment]
+1

**Comment by dlindahl** [comment]
@a-axton If you can bring this down to 10min, then it'd be a good fit for this month. OR you can do it next month if/when we do lightning talks, though it'd still be 10mins :blush:

**Comment by daltonamitchell** [comment]
This looks awesome! I'm already excited 👍

**Comment by a-axton** [comment]
putting this on hold, wanted to do a different topic for lightning talk
