### ISSUE TITLE
Lightning Talk Proposal: AngularJS $http vs. $resource

### ISSUE THREAD

**Issue by towen** [sacjs/sacjs.github.io#72]
Name: Terry J. Owen
Twitter Handle: iknowmac
GitHub Username: towen
Employer: Fullstack Labs
Talk Length: 5 min.

---

Title:  AngularJS $http vs. $resource
Brief Description: Discussion of the  benefits vs. drawbacks on use either $http or $resource when consuming RESTful web services with AngularJS.

**Comment by towen** [comment]
Sorry, need to move this to June due to scheduling.

**Comment by dlindahl** [comment]
Hey, no worries!
