### ISSUE TITLE
Lightning Talk Proposal: The Joy of Clothoid Curves

### ISSUE THREAD

**Issue by joeedh** [sacjs/sacjs.github.io#73]
Name: Joe Eagar
Twitter Handle: joeedh
GitHub Username: joeedh
Employer: want one
Talk Length: 5-10

---

Title: The Joy of Clothoid Curves
Brief Description: Clothoids are an exciting alternative to traditional Bezier curves.  Clothoids are great for logos, cartoon characters, 2D animation, and even steering self-driving cars.  This talk will demonstrate the sheer awesomeness of clothoids with a small app of mine, followed  by a brief introduction to the math if time allows.

**Comment by dlindahl** [comment]
Woah, this sounds cool! Just to remind you that our lightning talks have a hard cut-off at 5 minutes. Hopefully you can cram everything in such a short time period! If you think the talk went well and people want to hear more, maybe we can have you back for a more in-depth talk.  See you next week!
