### ISSUE TITLE
Lightning talk Proposal: But I just Learned Gulp :/

### ISSUE THREAD

**Issue by ivanvillacreative** [sacjs/sacjs.github.io#74]
Name: Ivan Villa
Twitter Handle: ivan_villa
GitHub Username: ivanvillacreative
Employer: Transmute - Creative Agency
Talk Length: 5 Minutes

---

Title: " But I just Learned Gulp :/ "
Brief Description: This talk would be about my views on the fast pace Web Dev world. New things are showing up each day, and it's easy to get overwhelmed. Hopefully, this will help put some minds at ease, because it's ok if your mom's website isn't built with react.

**Comment by dlindahl** [comment]
Glad to have you back! I did take some liberties with your description because Mom's have great ideas and deserve cool web tech too! 😄 If you want to revise what I changed, let me know!

**Comment by ivanvillacreative** [comment]
Haha, no that's perfectly fine :)

On Saturday, May 21, 2016, Derek Lindahl <notifications@github.com> wrote:

> Glad to have you back! I did take some liberties with your description
> because Mom's have great ideas and deserve cool web tech too! 😄 If you
> want to revise what I changed, let me know!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/sacjs/sacjs.github.io/issues/74#issuecomment-220816038>
>


-- 
*Ivan Villa*
*co-founder*
transmute.co
creative agency

*Cell* 530.902.9631
*Office* 916.222.0871
