### ISSUE TITLE
Talk Proposal: You should write tests

### ISSUE THREAD

**Issue by Bradcomp** [sacjs/sacjs.github.io#79]
Name: Brad Compton
Twitter Handle: @notpmoc84
GitHub Username: bradcomp
Employer: CLC Inc
Talk Length: 30 minutes (could do less or more if that works better)

---

Title:  You Should Write Tests
Brief Description:  
Why should we test our code?
Should we always write tests for our code?
What benefits do we gain from tests?
How can we write good tests?
Is TDD worth it?

We'll go over the benefits of testing, as well as how to get started writing a test suite for our JavaScript code, and some cool tools we can use to make our lives easier.

**Comment by dlindahl** [comment]
@Bradcomp - Hey-o! Sorry for the late response, I've been slammed. Are you still up for giving a talk next Tuesday?

**Comment by Bradcomp** [comment]
Hi Derek,

Unfortunately I can't next Tuesday!  I'd be happy to do it at a later meetup though.

**Comment by dlindahl** [comment]
No worries! Can you do Oct. 25?

**Comment by Bradcomp** [comment]
Sure! I can do that!  How long should I plan for?

**Comment by Bradcomp** [comment]
Just checking in.  Am I on for October 25th?  Should I plan for 30 minutes or 45?

**Comment by dlindahl** [comment]
@Bradcomp yes and let's shoot for 30!
