### ISSUE TITLE
Javascript & Java interoperation using Java 8 Nashorn

### ISSUE THREAD

**Issue by roboprog** [sacjs/sacjs.github.io#80]
Name:  Robin ("Rob") Anderson
Twitter Handle:  N/A
GitHub Username:  roboprog
Employer:  UC Davis Medical Center
Talk Length:  30 to 90 minutes, as needed

---

Title:  Mixing Javascript and Java
Brief Description:  This is a talk I gave at SacJUG a while back (http://sacjug.org/MeetingArchive2016.html#Year2016) about using the JS script execution tool that comes with Java 8, and about calling between JS and Java code in either direction.  This allows you to write server side code in Javascript while making use of a legacy code base.

https://docs.google.com/presentation/d/19KTud9_3I3MgJiYlVdF9SvCV8GcAvOFEjjY9ga0X3Y4/

**Comment by dlindahl** [comment]
@roboprog - An interesting proposal! 90 minutes is _way_ too long. Any chance you could get this down to 20mins?

**Comment by roboprog** [comment]
I could probably shorten this substantially if I omit presentation/discussion of calling from Java back into JS, and simply take the approach that one wants to write in Javascript, making use of all that old Java stuff that was left behind, and skip any discussion of running the debugger.
