### ISSUE TITLE
Immutable.js???

### ISSUE THREAD

**Issue by roboprog** [sacjs/sacjs.github.io#81]
Name:  Robin ("Rob") Anderson
Twitter Handle:  N/A
GitHub Username: roboprog
Employer: UC Davis Medical Center
Talk Length:  N/A - fishing/request

---

Title:  Info/demo for Immutable.js?
Brief Description:  Is anybody in the group using Immutable.js?  Do they have experiences and/or a demo to share?

**Comment by dlindahl** [comment]
@roboprog - Are you asking for more info on Immutable or are you proposing a specific talk?

**Comment by roboprog** [comment]
I know little to nothing about it, but it *sounds* interesting.  Just asking if anybody (somebody else) would volunteer if he/she knew it was of interest to others.
