### ISSUE TITLE
Talk Proposal

### ISSUE THREAD

**Issue by sungthecoder** [sacjs/sacjs.github.io#82]
Name: Sung Choi
Twitter Handle: @sychoi
GitHub Username: sungthecoder
Employer:
Talk Length: ~30min

---

Title: Brief History of JavaScript Module
Brief Description: Are you new to JavaScript and confused about modules, module loaders and module bundlers? Or you have been writing JavaScript code for a while, but can’t get a grip of the jargons about module? You heard about the jargons like CommonJS, AMD, Browserify, SystemJS, Webpack, JSPM, etc., but don’t understand why we need them?
I will try to explain what are they, and what problem they try to solve, and how they solve the problem. 

Slide: http://slides.com/sungthecoder/js-module-history/fullscreen

**Comment by dlindahl** [comment]
@sungthecoder Are you available to give this talk on the 22nd?

**Comment by sungthecoder** [comment]
Yes

**Comment by dlindahl** [comment]
@sungthecoder Awesome! I'll add you to the schedule!
