### ISSUE TITLE
Talk Proposal: A middle-aged man hacks Super Mario Bros. You won't believe what happens next.

### ISSUE THREAD

**Issue by cacciatc** [sacjs/sacjs.github.io#84]
Name: Chris Cacciatore
Twitter Handle: @cacciatc
GitHub Username: cacciatc
Employer: Chris Cacciatore
Talk Length: 20 min

---

Title: A middle-aged man hacks Super Mario Bros. You won't believe what happens next.
Brief Description: I talked with Derek a million years ago about programming the NES and he said that that could be a fun talk. I still would like to try that someday, but in the interim I propose something a little more fun--hacking SMB1 for the NES!

I will cover three different types of hacks:

* Game Genie tomfoolery (dynamic ROM editing).
* Text replacement and translation shenanigans (altering ROM).
* World Randomizer (altering ROM).

However, it's not all fun and games; expect to learn about the following topics:

* NES memory model.
* NES pattern tables.
* Some 6502 assembly programming.

What do you think? Would the crowd be in to it?

**Comment by dlindahl** [comment]
Does this involve any javascript at all? If not, that's totally OK! Though it'd be great if you could at least include something like "here is where you can integrate with JS, take a look at these things" with some links to any resources or ideas you may have like:

* https://github.com/bfirsh/jsnes
* http://www.nobadmemories.com/connectednes/
* anything from https://twitter.com/batslyadams

Sounds super interesting and I think the crowd will certainly be into it! I'll add you to the schedule!

**Comment by cacciatc** [comment]
Cool cool. I have some ideas for injecting some JavaScript into the pres; although that will prolly increase the time needed a little. Is it OK if I wonder into 20-25 min territory?

**Comment by dlindahl** [comment]
Yeah, you'll be ok at 20-25mins
