### ISSUE TITLE
Taming a dinosaur with JavaScript and Docker

### ISSUE THREAD

**Issue by decafdennis** [sacjs/sacjs.github.io#85]
Name: Dennis Stevense
Twitter Handle: https://twitter.com/decafdennis
GitHub Username: https://github.com/decafdennis
Employer: Digital Deployment
Talk Length: 10 minutes

---

Title: Taming a dinosaur with JavaScript and Docker
Brief Description: A brief overview of how we are using JavaScript and Docker to set up functional and visual regression testing for our Drupal 6 codebase.

**Comment by decafdennis** [comment]
@dlindahl I can be ready to give this talk this Tue night if you have a slot!

**Comment by dlindahl** [comment]
Sounds good! I'll add you to the schedule. See you tomorrow!
