### ISSUE TITLE
Lightning Talk proposal 12/20: Intro to building an Alexa skill

### ISSUE THREAD

**Issue by JoshuaMorris** [sacjs/sacjs.github.io#89]
Name: Joshua Morris
Twitter Handle: TheWoollyBully
GitHub Username: JoshuaMorris
Talk Length: 5 minutes

---

Title: Intro to building a basic Alexa Skill
Brief Description: Basic introduction to building an Alexa skill. I will show code from the Dad Jokes skill I submitted to the Alexa Skills Store and talk about how to a build a simple skill. If I have time today I will try and throw together a new skill I might be able to build in 5 minutes.

**Comment by dlindahl** [comment]
Thanks for the submission, this will be a great talk to have! Just an FYI, our first talk will be focusing on AWS Lambda, so it should be possible to skip over the basics of that

**Comment by JoshuaMorris** [comment]
It felt like it would pair nicely
