### ISSUE TITLE
Brian Holt: TBD

### ISSUE THREAD

**Issue by dlindahl** [sacjs/sacjs.github.io#90]
> [I contacted Brian via Twitter](https://twitter.com/sac_js/status/816411783321698304) to inquire about the possibility of him coming up to talk at a future SacJS meetup. After some discussion, we've pencilled in a date of March 28 for his visit.
>
> This is a WIP issue to discuss the logistics and details of Brian's talk

Name: Brian Holt
Twitter Handle: holtbt
GitHub Username: @btholt
Employer: Netflix
Talk Length: TBD

---

Title: TBD
Brief Description:
TBD

**Comment by dlindahl** [comment]
@btholt we usually do 3 20-minute, 2 30-minute, or 1 45-minute talks at out meetups. How much time will you need for your talk? If you're shooting for a shorter talk length, feel free to recruit some co-workers/friends to come up to help fill out our talk slots!

We'll also need a talk title and description for our meetup announcement.

Our event venue is:
[The Urban Hive](http://www.theurbanhive.com/)
1931 H St.
Sacramento, CA 95811

We usually start setting up around 6:30pm with a 7pm start.

As far as breweries go, if you have specific ones you want to check out, let me know. Otherwise, I'll come up with a list we can hit up. 🍻 

Let me know if you have any questions for us!

**Comment by btholt** [comment]
I'm still getting to this! I'm not sure I can rope another Netflixian into this but I'll check around. In any case, I think a 30 minute talk would suit me just fine.

**Comment by dlindahl** [comment]
Hey @btholt, wanted to ping you to see if we are still on for March 28? Anything you need from us to lock this in? Also, if you need to stay the night and Netflix won't cover it, let us know, we may have some options available.
