### ISSUE TITLE
Offline First Mobile Web Apps

### ISSUE THREAD

**Issue by chrisminnick** [sacjs/sacjs.github.io#91]
Name: Chris Minnick
Twitter Handle: chrisminnick
GitHub Username: chrisminnick
Employer: WatzThis?
Talk Length: 20-30min (could be longer if needed)

---

Title: Creating Offline First Mobile Web Apps
Brief Description: I'm just finishing writing and shooting a video course for Pluralsight about offline first mobile web apps. The course should be finished by Feb 28, and I'd like to come and talk about the idea of offline first and some of the things I learned and used while shooting this course, including IndexedDb, Service Workers, and lots of JavaScript trickery.

**Comment by dlindahl** [comment]
Sounds great!
