### ISSUE TITLE
Reactive programming in javascript using Rxjs

### ISSUE THREAD

**Issue by aravindkarnam** [sacjs/sacjs.github.io#92]
Name:
Twitter Handle:
GitHub Username: aravindkarnam
Employer: Student at sac state, intern at KPMG
Talk Length: 30 minutes

---

Title:
Brief Description:
RxJS is a library for composing asynchronous and event-based programs by using observable sequences. 
Think of RxJS as Lodash for events.

**Comment by dlindahl** [comment]
Sounds good! Looking forward to your talk!
