### ISSUE TITLE
Vue.js - Progressive JavaScript Framework or gateway drug?

### ISSUE THREAD

**Issue by daltonamitchell** [sacjs/sacjs.github.io#93]
Name: Dalton Mitchell
Twitter Handle: daltonamitchell
GitHub Username: daltonamitchell
Employer: OnlyWire
Talk Length: 20 min

---

Title: Vue.js - JavaScript framework or gateway drug?
Brief Description: Vue.js is a flexible JavaScript framework for quickly & easily building interactive UI components or SPAs. This talk will cover what I've learned while using Vue at work over the past few months. I'll explain how it's flexible nature allowed me to test the waters before fully diving in, and how it continues to be an easy tool of choice as our application size and complexity increases. By the end, I hope it will encourage some to give Vue.js a try on a small project and maybe get "hooked" like I did.

**Comment by samt** [comment]
Awesome job last night, thanks Dalton! (@daltonamitchell)
