### ISSUE TITLE
The JS Tooling Renaissance

### ISSUE THREAD

**Issue by tyleralves** [sacjs/sacjs.github.io#94]
Name: Tyler Alves
Twitter Handle: 
GitHub Username: tyleralves (bitbucket at the day job)
Employer: Synapse Group
Talk Length: 25 min
**Note:** I want time to find the best possible examples to demo so please don't schedule me in for March!!

---

Title: The JS Tooling Renaissance
Brief Description:
The Renaissance is considered by historians to be the period of time that served as a bridge between the middle ages and modern times. Well my fellow JS devs, after years of incremental gains we have reached the Renaissance of JS tooling. Even being spoiled by the cushy tooling setups available for the last few years, you will be blown away by the giant leap forward in developer experience that is now production ready!

This talk will be a one-slide powerpoint introducing the Typescript/ React/ Redux stack, and 20 minutes or so going through live production examples of the features that make it so productive: 
1. Hot Module Replacement: quick changes without having to perform all the actions required to reproduce state (ex: complex form validation logic), 
2. TS compiler: compiler errors are quick, runtime errors are slow, 
2a. IDE TS-compiler adoption: live parameter-type hints, instant type-error highlighting, method suggestions based on data type
3. React devtools shows data flow through entire app and helps identify exactly where bugs live (ex: fixing a bug by pinpointing location),
4. Redux devtools charts entire app state, allows time-travel debugging, and allows QA'ers to report bugs with state file, 
5. TSLint brief mention that a solid linter exists for TS

I'll make sure to include a brief side note that many of these ideas aren't original (see Elm), but each element of the stack has matured to a great extent and has massive production use and contribution.

**Comment by dlindahl** [comment]
Sounds good Tyler! Ping us when you've locked things in. We meet on the 4th Tuesday of the month putting our April meetup on the 25th.

**Comment by dlindahl** [comment]
Hey @tyleralves, you still on board for our April meetup?

**Comment by tyleralves** [comment]
@dlindahl Yessir. Playing with Elm for the last couple weeks makes me want to switch the stack but I'll stick with what I know for this one.
