### ISSUE TITLE
Erin McKean: Build an API in 20 minutes with Loopback

### ISSUE THREAD

**Issue by samt** [sacjs/sacjs.github.io#97]
> I spoke with Erin over lunch at IBM, she said she could come up to Sacramento to do a talk!

Name: **Erin McKean**
Twitter Handle: https://twitter.com/emckean
GitHub Username: @emckean
Employer: **IBM**
Talk Length: 20min

---

Title: **Build an API in 20 minutes with Loopback**

Brief Description:
Got data? Get a full CRUD API in 20 minutes with LoopBack! You'll learn:
* how to connect LoopBack to your datasource
* how to create a model
* how to add a custom method
* ... and more!

**Comment by emckean** [comment]
Title: Build an API in 20 minutes with Loopback
Brief Description: Got data? Get a full CRUD API in 20 minutes with LoopBack! You'll learn: 
-- how to connect LoopBack to your datasource
-- how to create a model
-- how to add a custom method
and more!

**Comment by samt** [comment]
Thanks @emckean! I've added in the talk information and the talk to our June 2017 Meetup Milestone.

**Comment by dlindahl** [comment]
@emckean Thanks again for coming up and sharing Loopback with us! It was great meeting you and good luck on that "new" BMW!
