### ISSUE TITLE
Build an intelligent chat bot using Google's api.ai and Express App

### ISSUE THREAD

**Issue by aravindkarnam** [sacjs/sacjs.github.io#98]
Name:
Twitter Handle:
GitHub Username: aravindkarnam
Employer: KPMG 
Talk Length: 30 to 40 minutes

---

Title:
Brief Description: Learn to build your own personal assistant like Jarvis in Iron Man, using Google's api.ai and express framework, and google home.

**Comment by dlindahl** [comment]
Are you available to give this talk at the June 27 meetup?

**Comment by aravindkarnam** [comment]
Sure

**Comment by dlindahl** [comment]
@aravindkarnam are you still free for this Tuesday, the 27th?

**Comment by aravindkarnam** [comment]
Yes, @dlindahl

**Comment by dlindahl** [comment]
@aravindkarnam Great! See you tomorrow!
